### ISSUE TITLE
How to train by my data

### ISSUE THREAD

**Issue by kuso10582** [sampritipanda/securimage_solver#5]
The code is use to 6 digits with alpha and digits
But I want to use by 4 digits with digits
so I need to train my own cnn
so the code can be used to train the data?

**Comment by ArionMiles** [comment]
You can!

Change the `$code_length` to 4
https://github.com/sampritipanda/securimage_solver/blob/master/securimage.php#L414

and `$charset` (remove the digits from the string)
https://github.com/sampritipanda/securimage_solver/blob/master/securimage.php#L429

then generate the files using `php secureimage_show.php`

**Comment by kuso10582** [comment]
I try to train for my data
but the answer always wrong
I use 10000 train_data and 4000 valid_data
Is my train_data too small?
And can I ask how to terminate the train? I always use ctrl+c, but sometimes will wrong.
And why image height and width are 46, 176 , not 80, 215?
My question is a bit more, thank you for your response.
